### ISSUE TITLE
Update to 1.9?

### ISSUE THREAD

**Issue by nubs** [ansible/ansible-docker-base#11]
Shouldn't stable be 1.9.0 now?  It would be nice for the 1.7 and 1.8 docker tags to also point to proper 1.7 and 1.8 versions.

**Comment by gimoh** [comment]
:+1:

**Comment by William-Yeh** [comment]
Original `stable-ubuntu14.04/Dockerfile` didn't pin any specific Ansible version:

```
apt-get install -y ansible
```

**Comment by gimoh** [comment]
@William-Yeh yip, a manually triggered re-build of the image would fix it, unless you think pinning the version would be a better idea (one way or another it requires manual intervention whenever a new version is out)

**Comment by William-Yeh** [comment]
As for the project itself (`ansible/ansible-docker-base` on GitHub), I don't think it necessary to pin the Ansible version.

As for the generated images hosted on Docker Hub, however, Ansible Inc has decided to put version tags on them (see https://registry.hub.docker.com/u/ansible/ubuntu14.04-ansible/tags/manage/ and https://registry.hub.docker.com/u/ansible/centos7-ansible/tags/manage/ ). So, the Dockerfiles should be re-written to properly reflect the correct image tags.

[Shameless plugs below]
As for my own Ansible images, I don't think it necessary to pin any specific Ansible version. Therefore, I've defined `williamyeh/ansible:xxx` images tags solely around Linux distributions, rather than Ansible versions. See https://registry.hub.docker.com/u/williamyeh/ansible/tags/manage/ for details.

**Comment by ptman** [comment]
If these images are in fact managed by Ansible Inc. they should be updated as part of the release process.

**Comment by geerlingguy** [comment]
:+1:

**Comment by trinitronx** [comment]
it looks like the `stable` tag is currently pointing at `1.9.2`

```
→ docker pull  ansible/centos7-ansible:stable
stable: Pulling from ansible/centos7-ansible
48e98da16d2c: Pull complete
5929e2fc236b: Pull complete
1e1b823eb9fb: Pull complete
4aa3c7e4da2b: Pull complete
13d67fc078af: Already exists
f1b10cd84249: Already exists
c852f6d61e65: Already exists
7322fbe74aa5: Already exists
Digest: sha256:938444fdf80c55ba560a6465161991c833b95bad8c8c704486625876b8a17f4f
Status: Downloaded newer image for ansible/centos7-ansible:stable

→ docker run -ti ansible/centos7-ansible:stable bash
[root@7b646b0691cb /]# ansible --version
ansible 1.9.2
  configured module search path = None
```

Thanks!

Looks like this issue should be closed :smile_cat:

**Comment by nubs** [comment]
`ansible/ubuntu14.04-ansible:stable` is 1.9.0.1 which is good enough to close this issue, but should probably be bumped to 1.9.2 as well.  It would be great if the images were published as part of the normal release process

**Comment by gregdek** [comment]
@nubs thanks for the PR.

Because of the variety of excellent Ansible Docker images on Dockerhub, we are deprecating our "official" Ansible Docker image. We will leave this repo active, but we will no longer accept pull requests or issues. Feel free to fork this repo and publish your own images to Dockerhub as you see fit. 

For a list of Ansible images on Dockerhub, you can look here: 

https://hub.docker.com/search/?q=ansible

Thanks!
