### ISSUE TITLE
Debian based image?

### ISSUE THREAD

**Issue by ypid** [ansible/ansible-docker-base#14]
What are your thoughts about an Debian based image?

**Comment by gregdek** [comment]
Initial thoughts: it's another image to support. :)

@abadger any notion of costs of doing this? Is it something we'd consider accepting a patch for?

**Comment by abadger** [comment]
We should talk to @jimi-c about what we want the future of these images to
be.

**Comment by gregdek** [comment]
I feel like it's an opportunity for community supported images to be a thing. Maybe after 2.0 we should discuss what that might look like.

**Comment by abadger** [comment]
:+1:

**Comment by gregdek** [comment]
thanks for the PR.

Because of the variety of excellent Ansible Docker images on Dockerhub, we are deprecating our "official" Ansible Docker image. We will leave this repo active, but we will no longer accept pull requests or issues. Feel free to fork this repo and publish your own images to Dockerhub as you see fit. 

For a list of Ansible images on Dockerhub, you can look here: 

https://hub.docker.com/search/?q=ansible

Thanks!
