### ISSUE TITLE
ansible-playbook output is displayed only after the command finishes

### ISSUE THREAD

**Issue by krisskross** [ansible/ansible-docker-base#15]
Running ansible-playbook (when building the docker image) display output only after the command finishes. This makes it less convenient to debug for larger playbooks.

Is there a way to display the output as the playbook executes, not after?

**Comment by gregdek** [comment]
@krisskross thanks for the PR.

Because of the variety of excellent Ansible Docker images on Dockerhub, we are deprecating our "official" Ansible Docker image. We will leave this repo active, but we will no longer accept pull requests or issues. Feel free to fork this repo and publish your own images to Dockerhub as you see fit. 

For a list of Ansible images on Dockerhub, you can look here: 

https://hub.docker.com/search/?q=ansible

Thanks!
