### ISSUE TITLE
How to reach the simple web server?

### ISSUE THREAD

**Issue by ttback** [ansible/ansible-docker-base#8]
when running `docker build -t webserver_simple .`, it failed at `Error unpacking rpm package httpd-2.4.6-19.el7.centos.x86_64` No reason mentioned

**Comment by abadger** [comment]
Hmm... my email describes a different question in this ticket.  Did you indeed get the build to work successfully but needed to know how to test out the web server?  If so, that answer is:

```
$ docker run webserver_simple
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
$ # You can cut and paste the ip from the message above:
$ curl http:// 172.17.0.2
<html>
<head>
<title>
  Created via Ansible Playbook
</title>
<body>
<h2>
  CentOS 7.0.1406 web server configured by ansible.
</h2>

</body>
</html>
```

For the question about building -- I haven't seen that error in the context of building the docker images before.  It would be generated by rpm or yum inside of the image, though. Not sure why that would be happening for you and not me unless there's a problem with the centos mirror that you're hitting from that host.

Perhaps try changing the example config to use the ubuntu base image and see if that works since ubuntu will be using different mirrors than centos.

**Comment by ttback** [comment]
thanks for the quick reply. I got the centos7 base and the webserver example mixed up. It ended up not working on my end to run the webserver playbook so I am kinda stuck at wondering why httpd-2.4.6-19.el7.centos.x86_6 failed to install. Is there any way to tweak it to try a diff version of httpd?

**Comment by abadger** [comment]
Depends on what's in the centos repository.  The line in the ansible playbook to tweak would be: https://github.com/ansible/ansible-docker-base/blob/master/examples/webserver-simple/ansible/site.yml#L12

If there's a different version of the httpd package in the centos repositories, you can specify the version of the package that you want there like ``` name=httpd-0:2.2.15-39.el6.centos.x86_64 state=present```  You could also try installing the package manually in a container to see if that shows whether the package is actually corrupted or not.

**Comment by ttback** [comment]
look like i could "ssh" into the container by doing docker attach and try the install commands manually first.  thanks for the tips.

**Comment by ttback** [comment]
i realize i have to `docker run -d -p 80 {image-name}` instead of just docker run -d {image-name}`, not too sure about the reason yet, but it seems like without specifying the port, I won't be able to access it on host's browser.

**Comment by gregdek** [comment]
@ttback thanks for the PR.

Because of the variety of excellent Ansible Docker images on Dockerhub, we are deprecating our "official" Ansible Docker image. We will leave this repo active, but we will no longer accept pull requests or issues. Feel free to fork this repo and publish your own images to Dockerhub as you see fit. 

For a list of Ansible images on Dockerhub, you can look here: 

https://hub.docker.com/search/?q=ansible

Thanks!
